services:
  biocypher-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/mcp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - biocypher-network

  biocypher-mcp-dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: ["uv", "run", "python", "deployment.py", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - biocypher-network

networks:
  biocypher-network:
    driver: bridge

volumes:
  logs:
